#!/bin/bash
# Publish the content-creator skill from the Obsidian vault into the manager
# plugin of this repo. The vault (claude/skills/content-creator) is the source
# of truth; the manager plugin carries the published copy so every agent with
# the manager plugin gets the single authoritative voice system.
# The skill itself is portable (relative links only); vault rule dependencies
# are vendored under references/_vault/ as mirrors — never hand-edit them.
set -euo pipefail

VAULT="${VAULT:-$HOME/workspace/obsidian-vaults/byheaven}"
SKILL_SRC="$VAULT/claude/skills/content-creator"
DEST="plugins/manager/skills/content-creator"

cd "$(dirname "$0")/.."

[ -d "$SKILL_SRC" ] || { echo "vault skill not found: $SKILL_SRC"; exit 1; }

rm -rf "$DEST"
cp -r "$SKILL_SRC" "$DEST"
mkdir -p "$DEST/references/_vault"
{
  echo "<!-- MIRROR of byheaven vault claude/rules/document-architecture-rules.md — do not hand-edit. Regenerated by scripts/publish-content-creator.sh -->"
  echo
  cat "$VAULT/claude/rules/document-architecture-rules.md"
} > "$DEST/references/_vault/document-architecture-rules.md"

echo "published $SKILL_SRC -> $DEST"
