#!/bin/bash
# Publish the content-creator skill from the Obsidian vault to this repo.
# The vault (claude/skills/content-creator) is the source of truth; this repo
# carries a self-contained copy at plugins/content-creator/skills/content-creator
# for vault-less consumers. The skill itself is portable (relative links only);
# vault rule dependencies are vendored under references/_vault/ as mirrors —
# never hand-edit them.
#
# The manager plugin does NOT bundle a copy: it references the skill by name
# (see plugins/manager/skills/manager/references/production.md) and expects
# the content-creator plugin installed alongside it.
set -euo pipefail

VAULT="${VAULT:-$HOME/workspace/obsidian-vaults/byheaven}"
SKILL_SRC="$VAULT/claude/skills/content-creator"
DEST="plugins/content-creator/skills/content-creator"

cd "$(dirname "$0")/.."

[ -d "$SKILL_SRC" ] || { echo "vault skill not found: $SKILL_SRC"; exit 1; }

rm -rf "$DEST"
cp -r "$SKILL_SRC" "$DEST"
mkdir -p "$DEST/references/_vault"
{
  echo "<!-- MIRROR of byheaven vault claude/rules/document-architecture-rules.md — do not hand-edit. Regenerated by scripts/publish-content-creator.sh -->"
  echo
  cat "$VAULT/claude/rules/document-architecture-rules.md"
} > "$DEST/references/_vault/document-architecture-rules.md"

echo "published $SKILL_SRC -> $DEST"
