#!/bin/bash
# Publish the content-creator skill from the Obsidian vault to this repo.
# The vault (claude/skills/content-creator) is the source of truth. This repo
# carries self-contained copies in two places:
#   1. plugins/content-creator/skills/content-creator  (standalone plugin)
#   2. plugins/manager/skills/content-creator          (bundled with manager)
# The skill itself is portable (relative links only); vault rule dependencies
# are vendored under references/_vault/ as mirrors — never hand-edit them.
set -euo pipefail

VAULT="${VAULT:-$HOME/workspace/obsidian-vaults/byheaven}"
SKILL_SRC="$VAULT/claude/skills/content-creator"
DESTS=(
  "plugins/content-creator/skills/content-creator"
  "plugins/manager/skills/content-creator"
)

cd "$(dirname "$0")/.."

[ -d "$SKILL_SRC" ] || { echo "vault skill not found: $SKILL_SRC"; exit 1; }

for DEST in "${DESTS[@]}"; do
  rm -rf "$DEST"
  cp -r "$SKILL_SRC" "$DEST"
  mkdir -p "$DEST/references/_vault"
  {
    echo "<!-- MIRROR of byheaven vault claude/rules/document-architecture-rules.md — do not hand-edit. Regenerated by scripts/publish-content-creator.sh -->"
    echo
    cat "$VAULT/claude/rules/document-architecture-rules.md"
  } > "$DEST/references/_vault/document-architecture-rules.md"
  echo "published $SKILL_SRC -> $DEST"
done
