#!/bin/bash
# Refresh the vault rule mirrors bundled with the content-creator skill.
# The skill itself is authored here, in plugins/manager/skills/content-creator;
# only the vault rules it depends on are mirrored under references/_vault/ so
# sessions without the vault (cloud, Codex elsewhere) can still read them.
# Never hand-edit a mirror; rerun this script after the vault rule changes.
set -euo pipefail

VAULT="${VAULT:-$HOME/Obsidian/byheaven}"
DEST="plugins/manager/skills/content-creator/references/_vault"
RULE="claude/rules/document-architecture-rules.md"

cd "$(dirname "$0")/.."

[ -f "$VAULT/$RULE" ] || { echo "vault rule not found: $VAULT/$RULE" >&2; exit 1; }

mkdir -p "$DEST"
# The notice goes after the YAML frontmatter so the mirror still parses as
# frontmatter-led Markdown for markdownlint.
NOTICE="<!-- MIRROR of byheaven vault $RULE — do not hand-edit. Regenerated by scripts/sync-vault-mirrors.sh -->"
awk -v notice="$NOTICE" '
  NR == 1 && $0 == "---" { infm = 1; print; next }
  infm && $0 == "---" { infm = 0; print; print ""; print notice; next }
  { print }
' "$VAULT/$RULE" > "$DEST/document-architecture-rules.md"

echo "refreshed $DEST/document-architecture-rules.md"
